name: reative_programing
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Paulo Silva <paulo.silva@conpay.com.br>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  rxdart: ^0.22.6
#  path: ^1.6.0

dev_dependencies: